version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.19.2
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"

  grafana:
    image: grafana/grafana:7.1.5
    volumes:
      - ./Grafana/Datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    ports:
      - 3000:3000
    depends_on:
      - prometheus
